name: 'Test nasm asdf plugin'

on: push
env:
    DEFAULT_NASM_VERSION: 2.16
    ASDF_BRANCH: v0.13.1

jobs:
    plugin_test_ubuntu:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: 'Test asdf install'
              uses: asdf-vm/actions/install@v2
              with:
                  tool_versions: 'nasm ${{ env.DEFAULT_NASM_VERSION }}'

            - name: asdf_plugin_test
              uses: asdf-vm/actions/plugin-test@v2
              with:
                  command: 'nasm --version'

            - name: 'Show plugins'
              run: 'asdf list'

            - name: 'Test asdf list-all'
              run: 'asdf list-all nasm'

    plugin_test_windows:
        runs-on: windows-latest
        defaults:
            run:
                shell: wsl-bash_Ubuntu-20.04 {0}
        env:
            ASDF_DIR: /root/.asdf
            ASDF_EXEC: /root/.asdf/bin/asdf
        steps:
            - uses: actions/checkout@v3
            - uses: Vampire/setup-wsl@v2
              with:
                  distribution: Ubuntu-20.04

            - name: 'Asdf installation'
              run: |
                  git config --global advice.detachedHead false
                  export ASDF_DIR=${{env.ASDF_DIR}}
                  git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch ${{ env.ASDF_BRANCH }}
                  sh $ASDF_DIR/asdf.sh
                  ${{env.ASDF_EXEC}} plugin add nasm https://github.com/Dpbm/asdf-nasm.git

            - name: 'Test list-all'
              run: '${{env.ASDF_EXEC}} list-all nasm'

            - name: 'Test install version'
              run: '${{env.ASDF_EXEC}} install nasm ${{env.DEFAULT_NASM_VERSION}}'

            - name: 'Test nasm version'
              run: 'nasm --version'

            - name: 'Show plugins'
              run: '${{env.ASDF_EXEC}} list'

    plugin_test_mac:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v3

            - name: 'Test asdf install'
              uses: asdf-vm/actions/install@v2
              with:
                  tool_versions: 'nasm ${{ env.DEFAULT_NASM_VERSION }}'

            - name: 'Test nasm version'
              run: 'nasm --version'

            - name: 'Show plugins'
              run: 'asdf list'

            - name: 'Test asdf list-all'
              run: 'asdf list-all nasm'
