name: 'Test nasm asdf plugin'

on: push
env:
    DEFAULT_NASM_VERSION: 2.16

jobs:
    plugin_test_ubuntu:
        runs-on: ubuntu-latest
        steps:
            - name: asdf_plugin_test
              uses: asdf-vm/actions/plugin-test@v2
              with:
                  command: 'nasm --version'

    plugin_test_windows:
        runs-on: windows-latest
        steps:
            - uses: Vampire/setup-wsl@v2
            - name: asdf_plugin_test
              uses: asdf-vm/actions/plugin-test@v2
              with:
                  command: 'nasm --version'

    plugin_test_mac:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v3

            - uses: asdf-vm/actions/install@v2
              with:
                  tool_versions: 'nasm ${{ env.DEFAULT_NASM_VERSION }}'

            - uses: asdf-vm/actions/plugin-test@v2
              with:
                  skip_install: true
                  plugin: nasm
                  command: 'nasm --version'
