name: 'Test nasm asdf plugin'

on: push
env:
    DEFAULT_NASM_VERSION: 2.16

jobs:
    plugin_test_ubuntu:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: 'Test asdf install'
              uses: asdf-vm/actions/install@v2
              with:
                  tool_versions: 'nasm ${{ env.DEFAULT_NASM_VERSION }}'

            - name: asdf_plugin_test
              uses: asdf-vm/actions/plugin-test@v2
              with:
                  command: 'nasm --version'

            - name: 'Show plugins'
              run: 'asdf list'

            - name: 'Test asdf list-all'
              run: 'asdf list-all nasm'

    plugin_test_windows:
        runs-on: windows-latest
        steps:
            - uses: Vampire/setup-wsl@v2
            - name: asdf_plugin_test
              uses: asdf-vm/actions/plugin-test@v2
              with:
                  command: 'nasm --version'

    plugin_test_mac:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v3

            - name: 'Test asdf install'
              uses: asdf-vm/actions/install@v2
              with:
                  tool_versions: 'nasm ${{ env.DEFAULT_NASM_VERSION }}'

            - name: 'Test nasm version'
              run: 'nasm --version'

            - name: 'Show plugins'
              run: 'asdf list'

            - name: 'Test asdf list-all'
              run: 'asdf list-all nasm'
